### ISSUE TITLE
How to connect with Grails Spring Security Facebook plugin ?

### ISSUE THREAD

**Issue by mmaryo** [agorapulse/grails-facebook-sdk#76]

**Comment by mariomatar** [comment]
Hi, 

I trie to use this plugin.

I connect with Spring Security Facebook

Then I display a page : 

	FacebookContext facebookContextProxy
	def test() {
        facebookContextProxy.user.exchangeToken()
		long userId = facebookContextProxy.user.id
		println userId
	}


The problem is userId is always 0

facebookContextProxy.user.exchangeToken()
facebookContextProxy.user.getToken()

userId stay 0


I getId() I see: 

    context.session.getData('userId')

So maybe I can pass variable throught session

But the problem is in FacebookContextUser

        long getId() {
            if (_id == -1) {
            }
            return _id
        }

and the _id is always 0


Can you help me

**Comment by benorama** [comment]
Do you use FB connect on a web site and connect though the FB JS SDK?
If you do, check that you have a cookie named `fbsr_${YOUR_APP_ID}` once you are authenticated.
The plugin detect this cookie and parse it to get userId / tokens.

**Comment by mariomatar** [comment]
Hi 

I use spring security facebook authentification plugin
I'll trie to add this cookie and give you a response 

Cheers

**Comment by benorama** [comment]
This cookie can only be set by Facebook JS SDK (FB.login method).
I suppose that Spring Security Facebook Authentication plugin already does that.
My recommandation would be to use only this plugin for authentication and use directly RestFB lib if you want to make Graph API calls?
